import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@/app/_ui/globals.css";
import Header from "./_ui/Header";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};
const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.className}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
